# Generated by Django 4.2.27 on 2026-09-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackFestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_slug', models.SlugField(default='hack-fest-26')),
                ('registration_type', models.CharField(choices=[('team', 'Team'), ('individual', 'Individual Builder')], default='team', max_length=20)),
                ('team_name', models.CharField(blank=True, max_length=120, null=True)),
                ('team_size', models.PositiveSmallIntegerField(default=1)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('institution', models.CharField(default='Daystar University', max_length=150)),
                ('is_daystar', models.BooleanField(default=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('campus', models.CharField(blank=True, max_length=50, null=True)),
                ('track_preference', models.CharField(blank=True, max_length=80, null=True)),
                ('role_preference', models.CharField(blank=True, max_length=80, null=True)),
                ('roster_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hack Fest Registration',
                'verbose_name_plural': 'Hack Fest Registrations',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hackfestregistration',
            constraint=models.UniqueConstraint(fields=('event_slug', 'email'), name='unique_hackfest_event_email'),
        ),
    ]
