# Generated by Django 4.2.27 on 2026-03-08 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_code", models.CharField(max_length=50)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateTimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(max_length=100)),
                ("duration_hours", models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("PPT", "Presentation (PPT/Slides)"),
                            ("DOC", "Word Document"),
                            ("XLS", "Excel Spreadsheet"),
                            ("IMG", "Image"),
                            ("ZIP", "Zip Archive"),
                            ("LINK", "External Link"),
                        ],
                        max_length=10,
                    ),
                ),
                ("link", models.URLField(blank=True, help_text="Link to Google Drive or Website", null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="resources/")),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
