# Generated by Django 5.2.8 on 2025-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_image_url_remove_payment_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(default='legacy-ref-001', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='0700000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
