# Generated by Django 5.2.8 on 2025-11-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_payment_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dita_official',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_paid_member',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
