# Generated by Django 5.2.8 on 2025-12-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_resource_file_alter_resource_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField(help_text='Must match build.gradle version code')),
                ('version_name', models.CharField(max_length=20)),
                ('apk_file', models.FileField(upload_to='updates/')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
