# Generated by Django 5.2.8 on 2025-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_appupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
