# Generated by Django 5.2.8 on 2025-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_examsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
