# Generated by Django 5.2.8 on 2025-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_examsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
