# Generated by Django 5.2.8 on 2025-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_examsession_exam_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('PPT', 'Presentation (PPT/Slides)'), ('DOC', 'Word Document'), ('XLS', 'Excel Spreadsheet'), ('IMG', 'Image'), ('ZIP', 'Zip Archive'), ('LINK', 'External Link')], max_length=10),
        ),
    ]
