# Generated by Django 5.2.8 on 2025-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_title', models.CharField(default='System Under Maintenance', max_length=100)),
                ('maintenance_message', models.TextField(default='We are currently upgrading our servers to make DITA even better. Please check back in a few minutes!')),
            ],
            options={
                'verbose_name_plural': 'App Configuration',
            },
        ),
    ]
