# Generated by Django 5.2.8 on 2025-12-07 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_communitypost_communitycomment_lostitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='likes',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
