# Generated by Django 5.2.8 on 2026-02-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_story_liked_by_storycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
