# Generated by Django 4.2.27 on 2026-03-06 11:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_story_video_alter_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='binary_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='binary_wins_easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='binary_wins_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='binary_wins_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ram_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ram_levels_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='snake_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='snake_high_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
