# Generated by Django 4.2.27 on 2026-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
