# Generated by Django 4.2.27 on 2026-03-08 12:38

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, null=True, upload_to="stories/")),
                (
                    "video",
                    cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="video"),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "liked_by",
                    models.ManyToManyField(blank=True, related_name="liked_stories", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stories", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "viewed_by",
                    models.ManyToManyField(blank=True, related_name="viewed_stories", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name_plural": "Stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="community.story"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LostItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("LOST", "Lost 🛑"), ("FOUND", "Found ✅")], default="LOST", max_length=10
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="lost_found/")),
                ("contact_phone", models.CharField(max_length=15)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic Help 📚"),
                            ("GENERAL", "General Chat 📢"),
                            ("MARKET", "Marketplace 💼"),
                            ("EVENTS", "Events & Fun 🎉"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="community_uploads/")),
                (
                    "liked_by",
                    models.ManyToManyField(blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.communitypost",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
